### ISSUE TITLE
关于The Split Strategy部分

### ISSUE THREAD

**Issue by lyb18758** [bytedance/E2STR#1]
论文中提及的Split Strategy部分，需要对样本进行分割和变换以获得子样本，请问在项目代码的哪部分进行了实现？

**Comment by prefixRAINSTARsuffix** [comment]
> 论文中提及的Split Strategy部分，需要对样本进行分割和变换以获得子样本，请问在项目代码的哪部分进行了实现？

定义在这个 [函数](https://github.com/bytedance/E2STR/blob/main/mmocr/models/textrecog/recognizers/flamingo.py#L258) 里

**Comment by lyb18758** [comment]
感谢回复，还有一个问题。请问vision encoder和language decoder的定义分别在哪？

**Comment by prefixRAINSTARsuffix** [comment]
> 感谢回复，还有一个问题。请问vision encoder和language decoder的定义分别在哪？

我们的模型结构与flamingo一致，直接使用的open-flamingo库来初始化模型，具体位置在 [模型初始化](https://github.com/bytedance/E2STR/blob/main/mmocr/models/textrecog/recognizers/flamingo.py#L141)
