### ISSUE TITLE
Some Problems in reproduce the code

### ISSUE THREAD

**Issue by Z-yolo** [bytedance/E2STR#3]
![1724395464623](https://github.com/user-attachments/assets/dc6efb4e-09f9-47b6-aba5-1d81f0491070)
Your work is very inspiring, but I'm having some problems reproducing it, such as the weights of the VIT model in Flamingo.py “ViT-B-4”, since there doesn't seem to be a weight parameter for this version at the moment!

**Comment by prefixRAINSTARsuffix** [comment]
> ![1724395464623](https://private-user-images.githubusercontent.com/56523995/360818896-dc6efb4e-09f9-47b6-aba5-1d81f0491070.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTYyNDMsIm5iZiI6MTcyNDM5NTk0MywicGF0aCI6Ii81NjUyMzk5NS8zNjA4MTg4OTYtZGM2ZWZiNGUtMDlmOS00N2I2LWFiYTUtMWQ4MWYwNDkxMDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA2NTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMWUyYzhhNWI3YjYyNDU0ZGI2ZTNlZjYzZWQzNzRiYzM3ZGI5MWFkMDkzNjZjMjEyNzBhN2NjY2E4NjEyNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uzW1_xFOZPRRvli-bmmkwuBHdiT0m9xY9fJCdQ_8e34) Your work is very inspiring, but I'm having some problems reproducing it, such as the weights of the VIT model in Flamingo.py “ViT-B-4”, since there doesn't seem to be a weight parameter for this version at the moment!

Yes. You have to modify this part in the open-flamingo library by adding a few lines of code. Please refer to the source code of "create_model_and_transforms" in the open-flamingo library.

**Comment by Z-yolo** [comment]
> > ![1724395464623](https://private-user-images.githubusercontent.com/56523995/360818896-dc6efb4e-09f9-47b6-aba5-1d81f0491070.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTYyNDMsIm5iZiI6MTcyNDM5NTk0MywicGF0aCI6Ii81NjUyMzk5NS8zNjA4MTg4OTYtZGM2ZWZiNGUtMDlmOS00N2I2LWFiYTUtMWQ4MWYwNDkxMDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA2NTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMWUyYzhhNWI3YjYyNDU0ZGI2ZTNlZjYzZWQzNzRiYzM3ZGI5MWFkMDkzNjZjMjEyNzBhN2NjY2E4NjEyNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uzW1_xFOZPRRvli-bmmkwuBHdiT0m9xY9fJCdQ_8e34) Your work is very inspiring, but I'm having some problems reproducing it, such as the weights of the VIT model in Flamingo.py “ViT-B-4”, since there doesn't seem to be a weight parameter for this version at the moment!
> 
> Yes. You have to modify this part in the open-flamingo library by adding a few lines of code. Please refer to the source code of "create_model_and_transforms" in the open-flamingo library.

Thank you for your reply, what you mean is that I need to find the relevant create_model_and_transforms code in the open-flamingo library and make some changes to it so that “ViT-B-4” can use MAE PRETRAIN WEIGHT?  because your readme.md configuration is to modify the MAE PRETRAIN WEIGHT PATH section.

**Comment by prefixRAINSTARsuffix** [comment]
> > > ![1724395464623](https://private-user-images.githubusercontent.com/56523995/360818896-dc6efb4e-09f9-47b6-aba5-1d81f0491070.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTYyNDMsIm5iZiI6MTcyNDM5NTk0MywicGF0aCI6Ii81NjUyMzk5NS8zNjA4MTg4OTYtZGM2ZWZiNGUtMDlmOS00N2I2LWFiYTUtMWQ4MWYwNDkxMDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA2NTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMWUyYzhhNWI3YjYyNDU0ZGI2ZTNlZjYzZWQzNzRiYzM3ZGI5MWFkMDkzNjZjMjEyNzBhN2NjY2E4NjEyNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uzW1_xFOZPRRvli-bmmkwuBHdiT0m9xY9fJCdQ_8e34) Your work is very inspiring, but I'm having some problems reproducing it, such as the weights of the VIT model in Flamingo.py “ViT-B-4”, since there doesn't seem to be a weight parameter for this version at the moment!
> > 
> > 
> > Yes. You have to modify this part in the open-flamingo library by adding a few lines of code. Please refer to the source code of "create_model_and_transforms" in the open-flamingo library.
> 
> Thank you for your reply, what you mean is that I need to find the relevant create_model_and_transforms code in the open-flamingo library and make some changes to it so that “ViT-B-4” can use MAE PRETRAIN WEIGHT? because your readme.md configuration is to modify the MAE PRETRAIN WEIGHT PATH section.

Yes. Simply adding a configuration (layer_num, width, num_head, etc) that supports the MAE weight.

**Comment by Z-yolo** [comment]
Thank you very much for every reply, I added the relevant configuration in Flamingo's library file create_model_and_transforms ---> open_clip.create_model_and_transforms, e.g. {
    “embed_dim": 768,
    “vision_cfg": {
        “image_size": [32, 128], {
        “layers": 12,
        “width": 768,
        “patch_size": 4
    },
    “text_cfg": {
        “context_length": 77,
        “vocab_size": 49408, ‘width’: 768, ‘patch_size’: 4 }, ‘text_cfg’: { ‘context_length’: 77, ‘vocab_size’: 49408,
        “width": 768,
        “heads": 12,
        “layers": 12
    }

}
But after many attempts, every time, before I can load the configuration for model creation, I already get a RuntimeError saying that this ViT-B-4 model configuration could not be found, and I really can't add it!

Could you please provide the details of the modification in your free time?

**Comment by prefixRAINSTARsuffix** [comment]
> Thank you very much for every reply, I added the relevant configuration in Flamingo's library file create_model_and_transforms ---> open_clip.create_model_and_transforms, e.g. { “embed_dim": 768, “vision_cfg": { “image_size": [32, 128], { “layers": 12, “width": 768, “patch_size": 4 }, “text_cfg": { “context_length": 77, “vocab_size": 49408, ‘width’: 768, ‘patch_size’: 4 }, ‘text_cfg’: { ‘context_length’: 77, ‘vocab_size’: 49408, “width": 768, “heads": 12, “layers": 12 }
> 
> } But after many attempts, every time, before I can load the configuration for model creation, I already get a RuntimeError saying that this ViT-B-4 model configuration could not be found, and I really can't add it!
> 
> Could you please provide the details of the modification in your free time?

You should add the configuration in open_clip/src/open_clip/model_configs.  (https://github.com/mlfoundations/open_clip/tree/main/src/open_clip/model_configs).
Also refer to this file (https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/factory.py).

I have leaved the company and I could not provide the original file that I modified. But feel free to ask if you meet further problems.

**Comment by Z-yolo** [comment]
Hi author, I've been bothering you before, thank you very much for your previous reply to help me run the training part of the code. 
However, I see that in the evaluation section, since I need to design the “JSON FILE FOR CHARACTER-WISE POSITION INFORMATION” and the " In-Context Pool", you mentioned in the readme that I can put the ” JSON FILE FOR CHARACTER-WISE POSITION INFORMATION” to None, but ”In-Context Pool" (i.e., a json file) by randomly sampling data from any target training set”, does it mean we can sample data as in-context pool by ourselves according to the JSON format you gave? Can this be used as an evaluation setup?

**Comment by prefixRAINSTARsuffix** [comment]
> Hi author, I've been bothering you before, thank you very much for your previous reply to help me run the training part of the code. However, I see that in the evaluation section, since I need to design the “JSON FILE FOR CHARACTER-WISE POSITION INFORMATION” and the " In-Context Pool", you mentioned in the readme that I can put the ” JSON FILE FOR CHARACTER-WISE POSITION INFORMATION” to None, but ”In-Context Pool" (i.e., a json file) by randomly sampling data from any target training set”, does it mean we can sample data as in-context pool by ourselves according to the JSON format you gave? Can this be used as an evaluation setup?

Yes. Please refer to our evaluation settings in Table 1 & 2. For example, if testing on WordArt, you can simply sample 100 examples from the training set of WordArt. You can also sample out-of-domain data, but the performance may be lower (refer to Table 5 in the supplementary).
